jatte/chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'


urlpatterns = [
    path('api/create-room/<str:uuid>/', views.create_room, name='create_room'),
    path('chat-admin/', views.admin, name='admin'),
    path('chat-admin/add-user/', views.add_user, name='add_user'),
    path('chat-admin/users/<uuid:uuid>/', views.user_detail, name='user_detail'),
    path('chat-admin/users/<uuid:uuid>/edit/', views.edit_user, name='edit_user'),
    path('chat-admin/<str:uuid>/', views.room, name='room'),
    path('chat-admin/<str:uuid>/delete/', views.delete_room, name='delete_room'),
]

jatte/jatte/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('', include('chat.urls')),
    path('', include('account.urls')),
    path('admin/', admin.site.urls),
]

jatte/account/models.py
import uuid

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.db import models
from django.utils import timezone


class CustomUserManager(UserManager):
    def _create_user(self, name, email, password, **extra_fields):
        if not email:
            raise ValueError("You have not provided a valid e-mail address")
        
        email = self.normalize_email(email)
        user = self.model(email=email, name=name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user
    
    def create_user(self, name=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(name, email, password, **extra_fields)
    
    def create_superuser(self, name=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(name, email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    AGENT = 'agent'
    MANAGER = 'manager'

    ROLES_CHOICES = (
        (AGENT, 'Agent'),
        (MANAGER, 'Manager'),
    )
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=255, blank=True, default='')
    role = models.CharField(max_length=20, choices=ROLES_CHOICES, default=AGENT)

    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

jatte/chat/models.py
from django.db import models

from account.models import User

class Message(models.Model):
    body = models.TextField()
    sent_by = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ('created_at',)

    def __str__(self):
        return f'{self.sent_by}'


class Room(models.Model):
    WAITING = 'waiting'
    ACTIVE = 'active'
    CLOSED = 'closed'

    CHOICES_STATUS = (
        (WAITING, 'Waiting'),
        (ACTIVE, 'Active'),
        (CLOSED, 'Closed'),
    )

    uuid = models.CharField(max_length=255, unique=True) # comes from front
    client = models.CharField(max_length=255)
    agent = models.ForeignKey(User, related_name='rooms', blank=True, null=True, on_delete=models.SET_NULL)
    messages = models.ManyToManyField(Message, blank=True)
    url = models.CharField(max_length=255, blank=True, null=True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=WAITING)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return f'{self.client} - {self.uuid}'

jatte/chat/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST

from account.forms import AddUserForm, EditUserForm
from account.models import User

from .models import Room



@require_POST
def create_room(request, uuid):
    name = request.POST.get('name', '')
    url = request.POST.get('url', '')

    Room.objects.create(uuid=uuid, client=name, url=url)

    return JsonResponse({'message': 'room created'})


@login_required
def admin(request):
    rooms = Room.objects.all()
    users = User.objects.filter(is_staff=True)

    return render(request, 'chat/admin.html', {'rooms': rooms, 'users': users})


@login_required
def room(request, uuid):
    room = Room.objects.get(uuid=uuid)

    if room.status == Room.WAITING:
        room.status = Room.ACTIVE
        room.agent = request.user
        room.save()

    return render(request, 'chat/room.html', {
        'room': room
    })


@login_required
def delete_room(request, uuid):
    if request.user.has_perm('room.delete_room'):
        room = Room.objects.get(uuid=uuid)
        room.delete()

        messages.success(request, 'Room deleted')
        return redirect('/chat-admin/')
    else:
        messages.error(request, 'You do not have permission to delete room.')

        return redirect('/chat-admin/')

@login_required
def user_detail(request, uuid):
    user = User.objects.get(pk=uuid)
    rooms = user.rooms.all()

    return render(request, 'chat/user_detail.html', {
        'user': user,
        'rooms': rooms
    })

@login_required
def edit_user(request, uuid):
    if request.user.has_perm('user.edit_user'):
        user = User.objects.get(pk=uuid)

        if request.method == 'POST':
            form = EditUserForm(request.POST, instance=user)

            if form.is_valid():
                form.save()

                messages.success(request, 'The changes was saved successfully')
                return redirect('/chat-admin/')
        else:
            form = EditUserForm(instance=user)

        return render(request, 'chat/edit_user.html', {
            'user': user,
            'form': form
        })
    else:
        messages.error(request, 'You do not have permission to edit users.')

        return redirect('/chat-admin/')

@login_required
def add_user(request):
    if request.user.has_perm('user.add_user'):
        if request.method == 'POST':
            form = AddUserForm(request.POST)

            if form.is_valid():
                user = form.save(commit=False)
                user.is_staff = True
                user.set_password(request.POST.get('password'))
                user.save()

                if user.role == User.MANAGER:
                    group = Group.objects.get(name='Managers')
                    group.user_set.add(user)

                messages.success(request, 'The user has been added!')

                return redirect('/chat-admin/')
        else:
            form = AddUserForm()
        return render(request, 'chat/add_user.html', {'form': form})

    else:
        messages.error(request, 'You are not allowed to add a user')

        return redirect('/chat-admin/')

jatte/chat/templates/chat/add_user.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-2xl">Add user</h1>

    <form method="post" action="." >
        {% csrf_token %}

        {{ form.as_p }}

        <button class="mt-6 inline-block py-2 px-6 bg-rose-600 text-white rounded-xl">Add user</button>
    </form>
{% endblock %}

jatte/chat/templates/chat/admin.html
{% extends 'core/base.html' %}

{% block content %}

    <h1 class="text-2xl">Chat admin</h1>

    {% if perms.user.add_user %} <!-- django built it check if user has a permission to add another users -->
        <div class="mt-8">
            <h2 class="mb-4 text-lg">Users</h2>

            <a href="{% url 'chat:add_user' %}" class="inline-block py-2 px-6 bg-rose-600 text-white rounded-xl">Add user</a>

            <div class="mt-6">
                {% for user in users %}
                    <div class="grid grid-cols-4 gap-4 py-2 {% cycle 'bg-gray-100' '' %}">
                        <p class="px-2">
                            <a href="{% url 'chat:user_detail' user.pk %}">{{ user.name }}</a>
                        </p>
                        <p class="px-2">{{ user.email }}</p>
                        <p class="px-2">{{ user.get_role_display }}</p>
                        <p class="px-2 text-right">
                            {% if perms.user.edit_user %}
                                <a href="{% url 'chat:edit_user' user.pk %}" class="underline">Edit</a>
                            {% endif %}
                        </p>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
    
    <hr class="my-6">

    <div class="mt-8">
        <h2 class="mb-4 text-lg">Rooms</h2>
        
        {% include 'chat/partials/room_list.html' %}
    </div>

    
    
{% endblock %}

jatte/chat/templates/chat/edit_user.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-2xl">Edit user</h1>

    <form method="post" action="." >
        {% csrf_token %}

        {{ form.as_p }}

        <button class="mt-6 inline-block py-2 px-6 bg-rose-600 text-white rounded-xl">Save changes</button>
    </form>
{% endblock %}

jatte/chat/templates/chat/room.html
{% extends 'core/base.html' %}

{% load static chatextras %}

{% block content %}

    <h1 class="text-2xl">Room "{{ room.uuid }}"</h1>

    <hr class="my-6">

    <p class="mb-6">
        <b>Name: </b>{{ room.client }}<br>
        <b>Started: </b>{{ room.created_at|timesince }}<br>
        <b>Status: </b>{{ room.get_status_display }}<br>
        <b>Page : </b>{{ room.url }}<br>
        <b>Agent: </b>{% firstof room.agent.name 'None yet...' %}

    </p>

    <hr class="mb-6">

    <div id="chat_log" class="mb-4 p-4 bg-gray-100 rounded-xl h-[300px] overflow-scroll flex flex-col flex-grow">
        {% for  message in  room.messages.all %}
            <div class="flex w-full max-w-md mt-2 space-x-3 {% if message.created_by %}ml-auto justify-end{% endif %}">
                {% if not message.created_by %}
                <div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-200 text-center pt-2">
                    {{ message.sent_by|initials }}
                </div>
                {% endif %}

                <div>
                    <div class="p-4 rounded-xl {% if message.created_by %}bg-blue-600 text-white{% else %}bg-gray-300{% endif %}">
                        <p class="text-sm">{{ message.body }}</p>
                    </div>
                    <span class="text-xs text-gray-500 leading-none">{{ message.created_at|timesince }} ago</span>
                </div>
                {% if message.created_by %}
                <div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-200 text-center pt-2">
                    {{ message.sent_by|initials }}
                </div>
                {% endif %}

            </div>

        {% endfor %}
    </div>

    {% if room.status == 'active' %}
        <input type="text" name="body" id="chat_message_input" class="w-full mb-4 p-4 bg-gray-100 rounded-xl" placeholder="Type your message...">
        <button id="chat_message_submit" class="py-2 px-6 bg-rose-600 text-white rounded-xl">Send</button>
    {% endif %}


{% endblock %}

{% block scripts %}
    {% if room.status == 'active' %}
        console.log({{room.uuid}} {{room.user.name}} {{room.user.ud}})
        {{ room.uuid|json_script:'room_uuid' }}
        {{ request.user.name|json_script:'user_name' }}
        {{ request.user.id|json_script:'user_id' }}

        <script src="{% static 'js/main_admin.js' %}"></script>
    {% endif %}
{% endblock %}

jatte/chat/templates/chat/user_detail.html
{% extends 'core/base.html' %}

{% block content %}

    <h1 class="text-2xl">{{ user.name }}</h1>

    <hr class="my-6">

    <div class="mt-8">
        <h2 class="mb-4 text-lg">Rooms</h2>
        
        {% include 'chat/partials/room_list.html' %}
    </div>

{% endblock %}