jatte/chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'


urlpatterns = [
    path('api/create-room/<str:uuid>/', views.create_room, name='create_room'),
    path('chat-admin/', views.admin, name='admin'),
    path('chat-admin/add-user/', views.add_user, name='add_user'),
    path('chat-admin/users/<uuid:uuid>/', views.user_detail, name='user_detail'),
    path('chat-admin/users/<uuid:uuid>/edit/', views.edit_user, name='edit_user'),
    path('chat-admin/<str:uuid>/', views.room, name='room'),
    path('chat-admin/<str:uuid>/delete/', views.delete_room, name='delete_room'),
]

jatte/core/urls.py
from django.urls import path

from . import views

app_name = 'core'


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

jatte/jatte/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('', include('chat.urls')),
    path('', include('account.urls')),
    path('admin/', admin.site.urls),
]

jatte/core/models.py
from django.db import models

# Create your models here.

jatte/core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'core/index.html')


def about(request):
    return render(request, 'core/about.html')

jatte/core/templates/core/about.html
{% extends 'core/base.html' %}

{% block content %}
<h1 class="mb-6 text-2xl">About</h1>
{% endblock %}

jatte/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>

<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/main.min.css' %}"
    />
  </head>

  <body>
    <div class="p-2">
      <nav
        class="p-6 bg-rose-600 text-white flex justify-between items-center rounded-xl"
      >
        <a href="{% url 'core:index' %}" class="text-xl">Jatte</a>

        <div class="flex items-center space-x-4">
          <a href="{% url 'core:index' %}">Home</a>
          <a href="{% url 'core:about' %}">About</a>

          {% if request.user.is_authenticated %}

            <a href="{% url 'chat:admin' %}" class="inline-block py-4 px-6 bg-rose-800 rounded-xl">Chat admin</a>

          {% endif %}

        </div>
      </nav>

      <main class="max-w-6xl mx-auto p-6">
        {% if messages %}
        <div class="message mb-6 p-6 bg-gray-800 text-white rounded-xl">
          {% for message in messages %}
          <p>{{ message }}</p>
          {% endfor %}
        </div>
        {% endif %} {% block content %} {% endblock %}
      </main>
    </div>

    <footer class="py-12 px-6 bg-gray-800 text-white text-center text-xs">
      <p>Copyright (c) 2023 - Jatte</p>
    </footer>

    {% block scripts %} {% endblock %}
  </body>
</html>

jatte/core/templates/core/index.html
{% extends 'core/base.html' %} {% load static %} {% block content %}
<div
  class="mt-12 py-12 px-8 grid grid-cols-5 gap-4 items-center border border-rose-200 rounded-xl"
>
  <div class="col-span-2">
    <img src="{% static 'images/header.png' %}" />
  </div>

  <div class="col-span-3">
    <h1 class="mb-8 text-3xl">Welcome to Jatte</h1>

    <h2 class="text-lg text-gray-500">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan
      tortor at sem fermentum tempor. Suspendisse vitae augue dolor. Nunc sed
      eleifend nulla.
    </h2>
  </div>
</div>

<div class="mt-12 py-12 px-8 grid grid-cols-3 gap-4 items-center">
  <div class="text-center">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="currentColor"
      class="w-12 h-12 mb-8 text-rose-600 mx-auto"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z"
      />
    </svg>

    <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

    <p class="text-gray-500">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan
      tortor at sem fermentum tempor.
    </p>
  </div>

  <div class="text-center">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="currentColor"
      class="w-12 h-12 mb-8 text-rose-600 mx-auto"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z"
      />
    </svg>

    <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

    <p class="text-gray-500">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan
      tortor at sem fermentum tempor.
    </p>
  </div>

  <div class="text-center">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="currentColor"
      class="w-12 h-12 mb-8 text-rose-600 mx-auto"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z"
      />
    </svg>

    <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

    <p class="text-gray-500">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan
      tortor at sem fermentum tempor.
    </p>
  </div>

  <div class="text-center">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="currentColor"
      class="w-12 h-12 mb-8 text-rose-600 mx-auto"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z"
      />
    </svg>

    <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

    <p class="text-gray-500">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan
      tortor at sem fermentum tempor.
    </p>
  </div>

  <div class="text-center">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="currentColor"
      class="w-12 h-12 mb-8 text-rose-600 mx-auto"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z"
      />
    </svg>

    <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

    <p class="text-gray-500">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan
      tortor at sem fermentum tempor.
    </p>
  </div>

  <div class="text-center">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="currentColor"
      class="w-12 h-12 mb-8 text-rose-600 mx-auto"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z"
      />
    </svg>

    <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

    <p class="text-gray-500">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan
      tortor at sem fermentum tempor.
    </p>
  </div>
</div>
{% include 'chat/partials/chat_bubble.html' %} {% endblock %}

{% block scripts %}
  <script src="{% static 'js/main.js' %}"></script>
{% endblock %}